version: '3'
services:
  otel-collector:
    container_name: firefly-collector
    image: firefly-collector
    command: ["./collector", "--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4433:4433 # AWS firehose receiver for metrics
      - 4318:4318 # OTLP HTTP receiver for traces
